[package]
name = "rust-HttpServer"
version = "0.1.0"
edition = "2024"

[dependencies]
threadpool = "1.8.1"                             # concurrent
flate2 = "1.1.2"                                 # gzip